import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, AlertTriangle, ArrowLeft, BarChart3, CalendarDays, FileSpreadsheet, FlaskConical, LineChart as LineChartIcon, Save, ShieldCheck, Trash2, Upload } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";

/**
 * Local research workspace only. This route does not write to scenario history,
 * does not call prediction APIs, and deliberately keeps calibrated probabilities,
 * raw shadow scores, and WHAT-IF scenario rates in distinct analysis paths.
 */
type ProbabilityKind = "truth_calibrated" | "shadow_score" | "what_if" | "unknown";
type FieldKey = "date" | "raceId" | "venue" | "modelId" | "probabilityKind" | "probability" | "shadowScore" | "odds" | "won" | "payout" | "predictionTime" | "oddsObservedAt" | "featureAsOf";
type Mapping = Record<FieldKey, string>;
type RawRow = Record<string, string>;
type AsOfStatus = "PASS" | "MISSING_EVIDENCE" | "FAIL";
type MarketStrategy = "odds_only" | "model_only" | "blend";
type ResearchRow = {
  date: string;
  raceId: string;
  venue: string;
  modelId: string;
  probabilityKind: ProbabilityKind;
  probability: number;
  shadowScore: number | null;
  odds: number | null;
  won: boolean;
  payout: number | null;
  asOfStatus: AsOfStatus;
  asOfReason: string;
};
type MappingProfile = { id: string; name: string; headers: string[]; mapping: Mapping; savedAt: number };
type MarketMetrics = { races: number; logLoss: number | null; brier: number | null };

const PROFILE_STORAGE_KEY = "keiba-lab-research-mapping-profiles-v1";
const fieldLabels: { key: FieldKey; label: string; required: boolean }[] = [
  { key: "date", label: "開催日", required: true }, { key: "raceId", label: "レースID", required: false }, { key: "venue", label: "競馬場", required: false }, { key: "modelId", label: "モデルID", required: false },
  { key: "probabilityKind", label: "確率種別", required: true }, { key: "probability", label: "予測確率（校正済み / WHAT-IF）", required: true }, { key: "shadowScore", label: "未校正shadow score（比較用）", required: false },
  { key: "odds", label: "発走前単勝オッズ", required: false }, { key: "won", label: "確定1着フラグ", required: true }, { key: "payout", label: "確定単勝払戻倍率（任意）", required: false },
  { key: "predictionTime", label: "予測時刻（as-of）", required: false }, { key: "oddsObservedAt", label: "オッズ取得時刻（as-of）", required: false }, { key: "featureAsOf", label: "特徴量時点（as-of）", required: false },
];
const aliases: Record<FieldKey, string[]> = {
  date: ["date", "race_date", "開催日", "日付", "競走年月日"], raceId: ["race_id", "raceid", "レースid", "race_key"], venue: ["venue", "track", "racecourse", "競馬場", "競馬場名", "開催場"],
  modelId: ["model_id", "model", "prediction_version", "モデルid"], probabilityKind: ["probability_kind", "probability_source", "prediction_type", "確率種別", "確率ソース"],
  probability: ["win_prob_calibrated", "probability", "pred_prob", "prediction", "win_rate", "予測確率", "勝率"], shadowScore: ["shadow_score", "raw_score", "uncalibrated_score", "shadow", "未校正スコア", "shadow score"],
  odds: ["odds", "win_odds", "decimal_odds", "単勝オッズ", "単勝"], won: ["won", "is_winner", "winner", "finish_position", "着順", "結果"], payout: ["win_payout", "payout_multiplier", "単勝払戻倍率", "払戻倍率"],
  predictionTime: ["prediction_time", "predicted_at", "予測時刻", "予測日時"], oddsObservedAt: ["odds_observed_at", "odds_time", "オッズ時刻", "オッズ取得時刻", "取得日時"], featureAsOf: ["feature_as_of", "features_asof", "特徴量時点", "データ時点"],
};
const kindLabel: Record<ProbabilityKind, string> = { truth_calibrated: "TRUTH PANEL 校正済み確率", shadow_score: "未校正 shadow score", what_if: "WHAT-IF シナリオ勝率", unknown: "種別未確認（分析対象外）" };
const strategyLabel: Record<MarketStrategy, string> = { odds_only: "odds-only", model_only: "model-only", blend: "blend" };
const initialMapping = {} as Mapping;

const readStorage = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const normalize = (value: string) => value.trim().toLowerCase().replace(/[\s_\-\/]/g, "");
const toNumber = (value: string | undefined) => { const result = Number(String(value ?? "").replace(/[,%]/g, "")); return Number.isFinite(result) ? result : null; };
const parseProbability = (value: string | undefined) => { const raw = toNumber(value); if (raw === null) return null; const probability = raw > 1 ? raw / 100 : raw; return probability > 0 && probability < 1 ? probability : null; };
const isWinner = (value: string | undefined) => ["1", "true", "win", "winner", "1着", "１着"].includes(String(value ?? "").trim().toLowerCase());
const toProbabilityKind = (value: string | undefined): ProbabilityKind => { const item = normalize(String(value ?? "")); if (["truthcalibrated", "calibrated", "winprobcalibrated", "校正済み"].includes(item)) return "truth_calibrated"; if (["shadowscore", "shadow", "uncalibrated", "未校正"].includes(item)) return "shadow_score"; if (["whatif", "simulation", "scenario", "シミュレーション"].includes(item)) return "what_if"; return "unknown"; };
const mappingValue = (row: RawRow, mapping: Mapping, key: FieldKey) => mapping[key] && mapping[key] !== "__none" ? row[mapping[key]] : undefined;
const normalizeDate = (value: string | undefined) => { const raw = String(value ?? "").trim().replace(/[/.]/g, "-"); const compact = raw.match(/^(\d{4})(\d{2})(\d{2})$/); const candidate = compact ? `${compact[1]}-${compact[2]}-${compact[3]}` : raw; return /^\d{4}-\d{2}-\d{2}$/.test(candidate) && !Number.isNaN(Date.parse(`${candidate}T00:00:00Z`)) ? candidate : null; };
const toTimestamp = (value: string | undefined) => { if (!value) return null; const normalized = String(value).trim().replace(/\//g, "-").replace(" ", "T"); const time = Date.parse(normalized); return Number.isFinite(time) ? time : null; };

function parseCsv(text: string): { headers: string[]; rows: RawRow[] } {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim());
  if (!lines.length) return { headers: [], rows: [] };
  const parseLine = (line: string) => { const cells: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { cells.push(value.trim()); value = ""; } else value += char; } cells.push(value.trim()); return cells; };
  const headers = parseLine(lines[0]);
  return { headers, rows: lines.slice(1).map((line) => Object.fromEntries(headers.map((header, index) => [header, parseLine(line)[index] ?? ""]))) };
}
function inferMapping(headers: string[]): Mapping { return Object.fromEntries(fieldLabels.map((field) => { const match = headers.find((header) => aliases[field.key].some((alias) => normalize(header) === normalize(alias))) ?? headers.find((header) => aliases[field.key].some((alias) => normalize(header).includes(normalize(alias)))); return [field.key, match ?? "__none"]; })) as Mapping; }
function asOfCheck(row: RawRow, mapping: Mapping): { status: AsOfStatus; reason: string } {
  const predictionTime = toTimestamp(mappingValue(row, mapping, "predictionTime"));
  const evidence = [["オッズ", toTimestamp(mappingValue(row, mapping, "oddsObservedAt"))], ["特徴量", toTimestamp(mappingValue(row, mapping, "featureAsOf"))]] as const;
  if (predictionTime === null) return { status: "MISSING_EVIDENCE", reason: "予測時刻が未指定" };
  const available = evidence.filter(([, value]) => value !== null);
  if (!available.length) return { status: "MISSING_EVIDENCE", reason: "オッズ・特徴量の時点が未指定" };
  const leaked = available.find(([, value]) => (value as number) > predictionTime);
  return leaked ? { status: "FAIL", reason: `${leaked[0]}時点が予測時刻より後` } : { status: "PASS", reason: "入力時点を確認" };
}
function normaliseRows(rows: RawRow[], mapping: Mapping): { valid: ResearchRow[]; rejected: number } {
  let rejected = 0;
  const valid = rows.flatMap((row, index) => {
    const probability = parseProbability(mappingValue(row, mapping, "probability")); const probabilityKind = toProbabilityKind(mappingValue(row, mapping, "probabilityKind")); const date = normalizeDate(mappingValue(row, mapping, "date"));
    if (!date || probability === null || probabilityKind === "unknown") { rejected += 1; return []; }
    const odds = toNumber(mappingValue(row, mapping, "odds")); const payout = toNumber(mappingValue(row, mapping, "payout")); const asOf = asOfCheck(row, mapping);
    return [{ date, raceId: mappingValue(row, mapping, "raceId") || `row-${index + 1}`, venue: mappingValue(row, mapping, "venue") || "未設定", modelId: mappingValue(row, mapping, "modelId") || "未指定", probabilityKind, probability, shadowScore: toNumber(mappingValue(row, mapping, "shadowScore")), odds: odds && odds > 1 ? odds : null, won: isWinner(mappingValue(row, mapping, "won")), payout: payout && payout > 0 ? payout : null, asOfStatus: asOf.status, asOfReason: asOf.reason }];
  }).sort((left, right) => left.date.localeCompare(right.date));
  return { valid, rejected };
}
function analyze(rows: ResearchRow[], fractionalKelly: number) {
  let capital = 100_000; let peak = capital;
  const curve = rows.map((row) => { const edge = row.odds ? row.probability * row.odds - 1 : null; const rawKelly = row.odds && edge && edge > 0 ? edge / (row.odds - 1) : 0; const stake = row.payout === null ? 0 : Math.floor(Math.min(capital * .02, capital * rawKelly * fractionalKelly) / 100) * 100; const profit = row.payout === null ? 0 : row.won ? stake * (row.payout - 1) : -stake; capital += profit; peak = Math.max(peak, capital); return { ...row, capital, drawdown: peak ? (capital - peak) / peak : 0, stake, profit }; });
  const brier = rows.length ? rows.reduce((sum, row) => sum + (row.probability - Number(row.won)) ** 2, 0) / rows.length : null;
  const logLoss = rows.length ? rows.reduce((sum, row) => { const p = Math.min(.999999, Math.max(.000001, row.probability)); return sum - (row.won ? Math.log(p) : Math.log(1 - p)); }, 0) / rows.length : null;
  const payouts = curve.filter((row) => row.payout !== null); const staked = payouts.reduce((sum, row) => sum + row.stake, 0); const returned = payouts.reduce((sum, row) => sum + row.stake + row.profit, 0);
  return { curve, brier, logLoss, hitRate: rows.length ? rows.filter((row) => row.won).length / rows.length : null, roi: staked > 0 ? returned / staked - 1 : null, payoutCoverage: payouts.length, maxDrawdown: curve.length ? Math.min(...curve.map((row) => row.drawdown)) : null };
}
function calibration(rows: ResearchRow[]) {
  const details = Array.from({ length: 10 }, (_, index) => { const low = index / 10; const high = (index + 1) / 10; const bucket = rows.filter((row) => row.probability >= low && (index === 9 ? row.probability <= high : row.probability < high)); if (!bucket.length) return null; const predicted = bucket.reduce((sum, row) => sum + row.probability, 0) / bucket.length; const observed = bucket.filter((row) => row.won).length / bucket.length; return { label: `${Math.round(low * 100)}–${Math.round(high * 100)}%`, predicted, observed, ideal: predicted, count: bucket.length, gap: predicted - observed }; }).filter((item): item is { label: string; predicted: number; observed: number; ideal: number; count: number; gap: number } => Boolean(item));
  const ece = rows.length ? details.reduce((sum, item) => sum + Math.abs(item.gap) * item.count / rows.length, 0) : null;
  return { details, ece };
}
function scoreComparison(rows: ResearchRow[]) { const paired = rows.filter((row) => row.probabilityKind === "truth_calibrated" && row.shadowScore !== null); if (!paired.length) return { paired, summary: null }; const scores = paired.map((row) => row.shadowScore as number); const probabilities = paired.map((row) => row.probability); const scoreMean = scores.reduce((a, b) => a + b, 0) / scores.length; const probabilityMean = probabilities.reduce((a, b) => a + b, 0) / probabilities.length; const numerator = scores.reduce((sum, score, index) => sum + (score - scoreMean) * (probabilities[index] - probabilityMean), 0); const scoreScale = Math.sqrt(scores.reduce((sum, score) => sum + (score - scoreMean) ** 2, 0)); const probabilityScale = Math.sqrt(probabilities.reduce((sum, probability) => sum + (probability - probabilityMean) ** 2, 0)); const correlation = scoreScale && probabilityScale ? numerator / (scoreScale * probabilityScale) : null; return { paired, summary: { count: paired.length, scoreMean, probabilityMean, correlation, observedRate: paired.filter((row) => row.won).length / paired.length } }; }
function normalizeProbabilities(values: number[]) { const safe = values.map((value) => Math.max(.000001, value)); const total = safe.reduce((sum, value) => sum + value, 0); return safe.map((value) => value / total); }
function logPool(model: number[], market: number[], marketWeight: number) { const values = model.map((value, index) => Math.exp((1 - marketWeight) * Math.log(Math.max(value, .000001)) + marketWeight * Math.log(Math.max(market[index], .000001)))); return normalizeProbabilities(values); }
function marketShadow(rows: ResearchRow[], marketWeight: number): { coverage: { eligibleRaces: number; skippedRaces: number; reason: string }; strategies: Record<MarketStrategy, MarketMetrics> } {
  const grouped = new Map<string, ResearchRow[]>(); rows.forEach((row) => grouped.set(row.raceId, [...(grouped.get(row.raceId) ?? []), row]));
  const values: Record<MarketStrategy, { losses: number[]; briers: number[] }> = { odds_only: { losses: [], briers: [] }, model_only: { losses: [], briers: [] }, blend: { losses: [], briers: [] } }; let skipped = 0;
  grouped.forEach((runners) => { if (runners.length < 2 || runners.some((row) => row.odds === null) || runners.filter((row) => row.won).length !== 1) { skipped += 1; return; } const market = normalizeProbabilities(runners.map((row) => 1 / (row.odds as number))); const model = normalizeProbabilities(runners.map((row) => row.probability)); const probabilities: Record<MarketStrategy, number[]> = { odds_only: market, model_only: model, blend: logPool(model, market, marketWeight) }; const winner = runners.findIndex((row) => row.won); (Object.keys(probabilities) as MarketStrategy[]).forEach((strategy) => { const p = probabilities[strategy]; values[strategy].losses.push(-Math.log(Math.max(p[winner], .000001))); values[strategy].briers.push(p.reduce((sum, value, index) => sum + (value - Number(index === winner)) ** 2, 0)); }); });
  const summarize = (item: { losses: number[]; briers: number[] }): MarketMetrics => ({ races: item.losses.length, logLoss: item.losses.length ? item.losses.reduce((a, b) => a + b, 0) / item.losses.length : null, brier: item.briers.length ? item.briers.reduce((a, b) => a + b, 0) / item.briers.length : null });
  return { coverage: { eligibleRaces: values.odds_only.losses.length, skippedRaces: skipped, reason: "同一レース内の全頭オッズ・ちょうど1頭の確定勝者・as-of検査通過が必要" }, strategies: { odds_only: summarize(values.odds_only), model_only: summarize(values.model_only), blend: summarize(values.blend) } };
}

export default function ResearchWorkbenchPage() {
  const [headers, setHeaders] = useState<string[]>([]); const [rawRows, setRawRows] = useState<RawRow[]>([]); const [mapping, setMapping] = useState<Mapping>(initialMapping); const [fileName, setFileName] = useState("未選択"); const [kind, setKind] = useState<ProbabilityKind>("truth_calibrated"); const [venue, setVenue] = useState("all"); const [modelId, setModelId] = useState("all"); const [dateStart, setDateStart] = useState(""); const [dateEnd, setDateEnd] = useState(""); const [fractionalKelly, setFractionalKelly] = useState(.25); const [marketWeight, setMarketWeight] = useState(.5); const [marketStrategy, setMarketStrategy] = useState<MarketStrategy>("blend"); const [notice, setNotice] = useState<string | null>(null); const [profileName, setProfileName] = useState(""); const [profiles, setProfiles] = useState<MappingProfile[]>(() => readStorage(PROFILE_STORAGE_KEY, []));
  useEffect(() => { localStorage.setItem(PROFILE_STORAGE_KEY, JSON.stringify(profiles)); }, [profiles]);
  const imported = useMemo(() => normaliseRows(rawRows, mapping), [rawRows, mapping]); const asOf = useMemo(() => ({ PASS: imported.valid.filter((row) => row.asOfStatus === "PASS").length, MISSING_EVIDENCE: imported.valid.filter((row) => row.asOfStatus === "MISSING_EVIDENCE").length, FAIL: imported.valid.filter((row) => row.asOfStatus === "FAIL").length }), [imported.valid]);
  const dates = useMemo(() => imported.valid.map((row) => row.date).sort(), [imported.valid]); const availableKinds = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.probabilityKind))), [imported.valid]); const venues = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.venue))).sort(), [imported.valid]); const models = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.modelId))).sort(), [imported.valid]);
  const filtered = useMemo(() => imported.valid.filter((row) => row.asOfStatus !== "FAIL" && row.probabilityKind === kind && (venue === "all" || row.venue === venue) && (modelId === "all" || row.modelId === modelId) && (!dateStart || row.date >= dateStart) && (!dateEnd || row.date <= dateEnd)), [imported.valid, kind, venue, modelId, dateStart, dateEnd]);
  const metrics = useMemo(() => analyze(filtered, fractionalKelly), [filtered, fractionalKelly]); const calibrationResult = useMemo(() => calibration(filtered), [filtered]); const comparison = useMemo(() => scoreComparison(imported.valid.filter((row) => row.asOfStatus !== "FAIL")), [imported.valid]); const market = useMemo(() => marketShadow(filtered.filter((row) => row.probabilityKind === "truth_calibrated"), marketWeight), [filtered, marketWeight]); const requiredMissing = fieldLabels.filter((field) => field.required && (!mapping[field.key] || mapping[field.key] === "__none")); const chartData = metrics.curve.map((row) => ({ date: row.date, capital: row.capital, drawdown: Number((row.drawdown * 100).toFixed(2)) }));
  const onUpload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".csv")) { setNotice("この研究画面はCSVのみをブラウザ内で読み込みます。"); return; } if (file.size > 20 * 1024 * 1024) { setNotice("CSVは20MB以下に分割してください。外部送信はしません。"); return; } const parsed = parseCsv(await file.text()); const nextMapping = inferMapping(parsed.headers); setHeaders(parsed.headers); setRawRows(parsed.rows); setMapping(nextMapping); setFileName(file.name); setVenue("all"); setModelId("all"); setDateStart(""); setDateEnd(""); setNotice("列マッピングとas-of検査を確認してください。確率種別が不明な行は除外します。"); };
  const saveProfile = () => { const name = profileName.trim(); if (!name || !headers.length) { setNotice("プロファイル名とCSVヘッダーが必要です。"); return; } const next = { id: `${Date.now()}`, name, headers, mapping, savedAt: Date.now() }; setProfiles((current) => [next, ...current.filter((profile) => profile.name !== name)].slice(0, 12)); setProfileName(""); setNotice(`マッピングプロファイル「${name}」をこのブラウザへ保存しました。`); };
  const applyProfile = (profile: MappingProfile) => { const unavailable = profile.headers.filter((header) => !headers.includes(header)); if (unavailable.length) { setNotice(`プロファイル「${profile.name}」は現在のCSVと一致しません（不足: ${unavailable.slice(0, 3).join("、")}）。`); return; } setMapping(profile.mapping); setNotice(`プロファイル「${profile.name}」を適用しました。`); };
  return <main className="min-h-screen bg-[#101719] px-4 py-6 text-[#ecf2ed] md:px-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 border-b border-[#315247] pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold tracking-[0.2em] text-[#8bb89a]">KEIBA LAB / RESEARCH WORKBENCH</p><h1 className="mt-2 text-3xl font-semibold">検証用バックテスト分析</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#b5c1b9]">TRUTH PANEL校正済み確率、未校正shadow score、WHAT-IFシナリオ勝率を分離したまま、時点固定・市場比較・再現可能なCSV分析を行います。</p></div><Link href="/" className="inline-flex items-center gap-2 self-start rounded border border-[#527566] px-3 py-2 text-sm text-[#d8e9dd] transition hover:bg-[#1d3029]"><ArrowLeft size={15} /> レースラボへ戻る</Link></header>
    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-3"><FileSpreadsheet className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">CSVを読み込む</h2><p className="mt-1 text-sm text-[#aebbb2]">必須: 開催日、確率種別、予測確率、確定1着フラグ。オッズ・払戻倍率は実データがある場合のみ研究用に集計します。</p></div></div><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded bg-[#2f766a] px-4 py-2 text-sm font-medium text-white transition hover:bg-[#3f8b7d]"><Upload size={15} /> CSVを選択<input className="hidden" type="file" accept=".csv,text/csv" onChange={onUpload} /></label><span className="ml-3 text-sm text-[#aebbb2]">{fileName}</span>{notice && <p className="mt-3 rounded border border-[#80663c] bg-[#332919] px-3 py-2 text-sm text-[#e9d2a0]">{notice}</p>}</div><aside className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2 text-[#8cc4a0]"><ShieldCheck size={17} /><span className="text-sm font-semibold">分離・時点固定ルール</span></div><ul className="mt-3 space-y-2 text-sm leading-5 text-[#b5c1b9]"><li>• 校正済み確率はブラウザ側で再校正しません。</li><li>• shadow scoreは順位・市場類似性だけに使います。</li><li>• WHAT-IFは実測確率・市場比較へ混ぜません。</li><li>• as-of失敗行は品質評価から除外します。</li></ul></aside></section>
    {headers.length > 0 && <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">列マッピングと再利用プロファイル</h2><p className="mt-1 text-sm text-[#aebbb2]">{rawRows.length.toLocaleString()}行読み込み。{requiredMissing.length ? `必須項目 ${requiredMissing.map((field) => field.label).join("、")} を確認してください。` : "必須項目を確認済みです。"}</p></div><span className="rounded bg-[#20332b] px-2 py-1 text-xs text-[#a9d7b8]">有効 {imported.valid.length.toLocaleString()}行 / 除外 {imported.rejected.toLocaleString()}行</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{fieldLabels.map((field) => <label key={field.key} className="text-sm"><span className="mb-1 block text-[#b5c1b9]">{field.label}{field.required && <b className="ml-1 text-[#e9b7a1]">必須</b>}</span><select className="w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={mapping[field.key] ?? "__none"} onChange={(event) => setMapping((current) => ({ ...current, [field.key]: event.target.value }))}><option value="__none">未使用</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="mt-5 border-t border-[#315247] pt-4"><div className="flex flex-wrap gap-2"><input className="rounded border border-[#456357] bg-[#101719] px-3 py-2 text-sm text-[#ecf2ed]" value={profileName} onChange={(event) => setProfileName(event.target.value)} placeholder="例: JRA-VAN 成績CSV v1" /><button type="button" onClick={saveProfile} className="inline-flex items-center gap-2 rounded bg-[#2f766a] px-3 py-2 text-sm font-medium"><Save size={14} /> 現在の対応を保存</button></div>{profiles.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{profiles.map((profile) => <span key={profile.id} className="inline-flex items-center gap-1 rounded border border-[#456357] bg-[#101719] px-2 py-1 text-xs"><button type="button" onClick={() => applyProfile(profile)} className="text-[#c7e5d0] hover:underline">{profile.name}</button><button type="button" onClick={() => setProfiles((current) => current.filter((item) => item.id !== profile.id))} aria-label={`${profile.name}を削除`} className="text-[#d98c78]"><Trash2 size={12} /></button></span>)}</div>}</div></section>}
    {imported.valid.length > 0 && <><section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#8cc4a0]" /><h2 className="font-semibold">評価範囲とas-of検査</h2></div><div className="mt-4 grid gap-3 md:grid-cols-5"><label className="text-sm text-[#b5c1b9]">開始日<input className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" type="date" min={dates[0]} max={dateEnd || dates.at(-1)} value={dateStart} onChange={(event) => setDateStart(event.target.value)} /></label><label className="text-sm text-[#b5c1b9]">終了日<input className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" type="date" min={dateStart || dates[0]} max={dates.at(-1)} value={dateEnd} onChange={(event) => setDateEnd(event.target.value)} /></label><label className="text-sm text-[#b5c1b9]">確率種別<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={kind} onChange={(event) => setKind(event.target.value as ProbabilityKind)}>{availableKinds.map((item) => <option key={item} value={item}>{kindLabel[item]}</option>)}</select></label><label className="text-sm text-[#b5c1b9]">競馬場<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={venue} onChange={(event) => setVenue(event.target.value)}><option value="all">全競馬場</option>{venues.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="text-sm text-[#b5c1b9]">モデルID<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={modelId} onChange={(event) => setModelId(event.target.value)}><option value="all">全モデル</option>{models.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded border border-[#315247] bg-[#101719] p-3"><span className="text-xs text-[#9bb0a4]">as-of PASS</span><strong className="ml-2 text-[#92d5aa]">{asOf.PASS}</strong></div><div className="rounded border border-[#315247] bg-[#101719] p-3"><span className="text-xs text-[#9bb0a4]">時点情報なし</span><strong className="ml-2 text-[#e7bc62]">{asOf.MISSING_EVIDENCE}</strong></div><div className="rounded border border-[#6e4138] bg-[#2c1d1a] p-3"><span className="text-xs text-[#d9a095]">as-of FAIL（除外）</span><strong className="ml-2 text-[#e89987]">{asOf.FAIL}</strong></div></div></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{[["対象行", filtered.length.toLocaleString()], ["Brier", metrics.brier?.toFixed(4) ?? "データなし"], ["Log loss", metrics.logLoss?.toFixed(4) ?? "データなし"], ["ECE", calibrationResult.ece?.toFixed(4) ?? "データなし"], ["実績的中率", metrics.hitRate === null ? "データなし" : `${(metrics.hitRate * 100).toFixed(1)}%`], ["ROI", metrics.roi === null ? "払戻なし" : `${(metrics.roi * 100).toFixed(1)}%`], ["最大DD", metrics.maxDrawdown === null ? "払戻なし" : `${(metrics.maxDrawdown * 100).toFixed(1)}%`]].map(([label, value]) => <div className="rounded-lg border border-[#315247] bg-[#17211f] p-4" key={label}><p className="text-xs text-[#9bb0a4]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</section>
      <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><Activity size={17} className="text-[#8cc4a0]" /><div><h2 className="font-semibold">確率校正曲線と理想線</h2><p className="text-xs text-[#aebbb2]">{kindLabel[kind]}のみ。ECEは確率帯の絶対gapを件数加重した研究指標です。</p></div></div><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={calibrationResult.details}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis dataKey="label" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis domain={[0, 1]} tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${Math.round(value * 100)}%`} /><Tooltip contentStyle={{ background: "#101719", border: "1px solid #456357" }} formatter={(value: number) => `${(value * 100).toFixed(1)}%`} /><Line type="monotone" dataKey="ideal" name="理想線（予測確率）" stroke="#9ba79f" strokeDasharray="5 4" dot={false} /><Line type="monotone" dataKey="observed" name="実績的中率" stroke="#68c197" strokeWidth={2} connectNulls /></LineChart></ResponsiveContainer></div><p className="mt-2 text-xs text-[#91a59a]">確率帯ごとの件数: {calibrationResult.details.map((row) => row.count).join(" / ") || "データなし"}</p></article><article className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><BarChart3 size={17} className="text-[#8cc4a0]" /><div><h2 className="font-semibold">資金・ドローダウン</h2><p className="text-xs text-[#aebbb2]">確定払戻倍率のある履歴だけ。Fractional Kellyは研究用表示です。</p></div></div><label className="mt-3 block text-sm text-[#b5c1b9]">Fractional Kelly: {fractionalKelly.toFixed(2)}<input className="mt-2 w-full accent-[#5eb782]" type="range" min="0" max=".5" step=".05" value={fractionalKelly} onChange={(event) => setFractionalKelly(Number(event.target.value))} /></label><div className="mt-4 h-60">{metrics.payoutCoverage ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fill: "#aebbb2", fontSize: 10 }} /><YAxis yAxisId="capital" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis yAxisId="dd" orientation="right" tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={{ background: "#101719", border: "1px solid #456357" }} /><ReferenceLine yAxisId="dd" y={0} stroke="#6d8477" /><Area yAxisId="capital" type="monotone" dataKey="capital" name="資金" stroke="#68c197" fill="#68c197" fillOpacity={.12} /><Area yAxisId="dd" type="monotone" dataKey="drawdown" name="DD%" stroke="#d67a68" fill="#d67a68" fillOpacity={.15} /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-[#aebbb2]">確定単勝払戻倍率を読み込むと資金曲線を表示します。</div>}</div></article></section>
      <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-2"><LineChartIcon size={17} className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">Market shadow — odds-only / model-only / blend</h2><p className="mt-1 text-xs leading-5 text-[#aebbb2]">校正済みTRUTH PANEL確率と同一レース内の発走前単勝オッズを使うshadow比較です。未校正shadow scoreとWHAT-IFはこの評価へ含めません。</p></div></div><div className="mt-4 flex flex-wrap items-center gap-2">{(Object.keys(strategyLabel) as MarketStrategy[]).map((strategy) => <button key={strategy} type="button" onClick={() => setMarketStrategy(strategy)} className={`rounded px-3 py-2 text-sm ${marketStrategy === strategy ? "bg-[#2f766a] text-white" : "border border-[#456357] text-[#c4d7ca]"}`}>{strategyLabel[strategy]}</button>)}<label className="ml-auto text-sm text-[#b5c1b9]">市場重み（blend）: {marketWeight.toFixed(2)}<input className="ml-2 align-middle accent-[#5eb782]" type="range" min="0" max="1" step=".05" value={marketWeight} onChange={(event) => setMarketWeight(Number(event.target.value))} /></label></div><div className="mt-4 grid gap-3 md:grid-cols-3">{(Object.keys(strategyLabel) as MarketStrategy[]).map((strategy) => <div key={strategy} className={`rounded border p-4 ${strategy === marketStrategy ? "border-[#69ad7e] bg-[#1c3028]" : "border-[#315247] bg-[#101719]"}`}><p className="text-sm font-semibold">{strategyLabel[strategy]}</p><p className="mt-2 text-xs text-[#9bb0a4]">対象レース {market.strategies[strategy].races}</p><p className="mt-1 text-sm">Log loss: {market.strategies[strategy].logLoss?.toFixed(4) ?? "データなし"}</p><p className="mt-1 text-sm">Brier: {market.strategies[strategy].brier?.toFixed(4) ?? "データなし"}</p></div>)}</div><p className="mt-3 text-xs text-[#91a59a]">{market.coverage.reason}。対象 {market.coverage.eligibleRaces}レース / 除外 {market.coverage.skippedRaces}レース。優位性の結論は、同一未来期間のwalk-forward集計と統計検定で判断します。</p></section>
      <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-2"><FlaskConical size={17} className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">TRUTH PANEL × shadow score 比較</h2><p className="mt-1 text-xs leading-5 text-[#aebbb2]">同一行の校正済み確率と未校正scoreの関係を確認します。shadow scoreは確率・Brier・Log loss・ROIの計算には使用しません。</p></div></div>{comparison.summary ? <><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["ペア行数", comparison.summary.count.toLocaleString()], ["校正済み確率平均", `${(comparison.summary.probabilityMean * 100).toFixed(1)}%`], ["shadow score平均", comparison.summary.scoreMean.toFixed(3)], ["相関の参考値", comparison.summary.correlation === null ? "算出不可" : comparison.summary.correlation.toFixed(3)], ["ペア行の実績的中率", `${(comparison.summary.observedRate * 100).toFixed(1)}%`]].map(([label, value]) => <div key={label} className="rounded border border-[#315247] bg-[#101719] p-3"><p className="text-xs text-[#9bb0a4]">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 16, bottom: 10, left: 0 }}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis type="number" dataKey="shadowScore" name="未校正shadow score" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis type="number" dataKey="probability" name="校正済み確率" domain={[0, 1]} tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${Math.round(value * 100)}%`} /><ZAxis range={[45, 45]} /><Tooltip cursor={{ strokeDasharray: "3 3" }} contentStyle={{ background: "#101719", border: "1px solid #456357" }} formatter={(value: number, name: string) => name === "校正済み確率" ? `${(value * 100).toFixed(1)}%` : value.toFixed(3)} /><Scatter name="校正済み確率とshadow score" data={comparison.paired} fill="#e7bc62" /></ScatterChart></ResponsiveContainer></div></> : <p className="mt-4 rounded border border-dashed border-[#456357] px-4 py-5 text-sm text-[#aebbb2]">比較対象はありません。`truth_calibrated`と同一行の`shadow_score`をマッピングしてください。</p>}</section></>}
    {headers.length === 0 && <section className="rounded-lg border border-dashed border-[#456357] bg-[#17211f] p-10 text-center"><AlertTriangle className="mx-auto text-[#e7bc62]" /><h2 className="mt-3 font-semibold">CSVを選択すると研究用分析を開始できます</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-[#aebbb2]">JRA-VAN等から正当に取得・エクスポートした履歴を利用してください。確率・市場・払戻・時点情報が不足する場合は、推測せず対象外または入力不足として扱います。</p></section>}
  </div></main>;
}
