import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, AlertTriangle, ArrowLeft, BarChart3, CalendarDays, Download, FileSpreadsheet, FileUp, FlaskConical, LineChart as LineChartIcon, Save, Search, ShieldCheck, SlidersHorizontal, Trash2, Upload } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";

/** Local research-only workspace. It does not modify prediction APIs, model state, or WHAT-IF history. */
type ProbabilityKind = "truth_calibrated" | "shadow_score" | "what_if" | "unknown";
type FieldKey = "date" | "raceId" | "venue" | "modelId" | "probabilityKind" | "probability" | "shadowScore" | "odds" | "won" | "payout" | "predictionTime" | "oddsObservedAt" | "featureAsOf";
type Mapping = Record<FieldKey, string>;
type RawRow = Record<string, string>;
type AsOfStatus = "PASS" | "MISSING_EVIDENCE" | "FAIL";
type MarketStrategy = "odds_only" | "model_only" | "blend";
type AnalysisTab = "metrics" | "asof";
type ResearchRow = { date: string; raceId: string; venue: string; modelId: string; probabilityKind: ProbabilityKind; probability: number; shadowScore: number | null; odds: number | null; won: boolean; payout: number | null; asOfStatus: AsOfStatus; asOfReason: string };
type MappingProfile = { id: string; name: string; headers: string[]; mapping: Mapping; savedAt: number };
type MappingProfileExport = { format: "keiba-lab-research-mapping-profiles-v1"; exportedAt: string; profiles: MappingProfile[] };
type MarketMetrics = { races: number; logLoss: number | null; brier: number | null };

const PROFILE_STORAGE_KEY = "keiba-lab-research-mapping-profiles-v1";
const EPS = 0.000001;
const fieldLabels: { key: FieldKey; label: string; required: boolean }[] = [
  { key: "date", label: "開催日", required: true }, { key: "raceId", label: "レースID", required: false }, { key: "venue", label: "競馬場", required: false }, { key: "modelId", label: "モデルID", required: false },
  { key: "probabilityKind", label: "確率種別", required: true }, { key: "probability", label: "予測確率（校正済み / WHAT-IF）", required: true }, { key: "shadowScore", label: "未校正shadow score（比較用）", required: false },
  { key: "odds", label: "発走前単勝オッズ", required: false }, { key: "won", label: "確定1着フラグ", required: true }, { key: "payout", label: "確定単勝払戻倍率（任意）", required: false },
  { key: "predictionTime", label: "予測時刻（as-of）", required: false }, { key: "oddsObservedAt", label: "オッズ取得時刻（as-of）", required: false }, { key: "featureAsOf", label: "特徴量時点（as-of）", required: false },
];
const aliases: Record<FieldKey, string[]> = {
  date: ["date", "race_date", "開催日", "日付", "競走年月日"], raceId: ["race_id", "raceid", "レースid", "race_key"], venue: ["venue", "track", "racecourse", "競馬場", "競馬場名", "開催場"], modelId: ["model_id", "model", "prediction_version", "モデルid"],
  probabilityKind: ["probability_kind", "probability_source", "prediction_type", "確率種別", "確率ソース"], probability: ["win_prob_calibrated", "probability", "pred_prob", "prediction", "win_rate", "予測確率", "勝率"], shadowScore: ["shadow_score", "raw_score", "uncalibrated_score", "shadow", "未校正スコア", "shadow score"],
  odds: ["odds", "win_odds", "decimal_odds", "単勝オッズ", "単勝"], won: ["won", "is_winner", "winner", "finish_position", "着順", "結果"], payout: ["win_payout", "payout_multiplier", "単勝払戻倍率", "払戻倍率"],
  predictionTime: ["prediction_time", "predicted_at", "予測時刻", "予測日時"], oddsObservedAt: ["odds_observed_at", "odds_time", "オッズ時刻", "オッズ取得時刻", "取得日時"], featureAsOf: ["feature_as_of", "features_asof", "特徴量時点", "データ時点"],
};
const kindLabel: Record<ProbabilityKind, string> = { truth_calibrated: "TRUTH PANEL 校正済み確率", shadow_score: "未校正 shadow score", what_if: "WHAT-IF シナリオ勝率", unknown: "種別未確認（分析対象外）" };
const strategyLabel: Record<MarketStrategy, string> = { odds_only: "odds-only", model_only: "model-only", blend: "blend" };
const normalize = (value: string) => value.trim().toLowerCase().replace(/[\s_\-/]/g, "");
const toNumber = (value?: string) => { const n = Number(String(value ?? "").replace(/[,%]/g, "")); return Number.isFinite(n) ? n : null; };
const parseProbability = (value?: string) => { const n = toNumber(value); if (n === null) return null; const p = n > 1 ? n / 100 : n; return p > 0 && p < 1 ? p : null; };
const isWinner = (value?: string) => ["1", "true", "win", "winner", "1着", "１着"].includes(String(value ?? "").trim().toLowerCase());
const toProbabilityKind = (value?: string): ProbabilityKind => { const item = normalize(String(value ?? "")); if (["truthcalibrated", "calibrated", "winprobcalibrated", "校正済み"].includes(item)) return "truth_calibrated"; if (["shadowscore", "shadow", "uncalibrated", "未校正"].includes(item)) return "shadow_score"; if (["whatif", "simulation", "scenario", "シミュレーション"].includes(item)) return "what_if"; return "unknown"; };
const toTimestamp = (value?: string) => { if (!value?.trim()) return null; const t = Date.parse(value.trim().replace(/\//g, "-").replace(" ", "T")); return Number.isFinite(t) ? t : null; };
const readStorage = <T,>(key: string, fallback: T): T => { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };
const readMapped = (row: RawRow, mapping: Mapping, key: FieldKey) => mapping[key] && mapping[key] !== "__none" ? row[mapping[key]] : undefined;
const normalizeDate = (value?: string) => { const raw = String(value ?? "").trim().replace(/[/.]/g, "-"); const compact = raw.match(/^(\d{4})(\d{2})(\d{2})$/); const result = compact ? `${compact[1]}-${compact[2]}-${compact[3]}` : raw; return /^\d{4}-\d{2}-\d{2}$/.test(result) && !Number.isNaN(Date.parse(`${result}T00:00:00Z`)) ? result : null; };

function parseCsv(text: string): { headers: string[]; rows: RawRow[] } {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim());
  if (!lines.length) return { headers: [], rows: [] };
  const parseLine = (line: string) => { const cells: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { cells.push(value.trim()); value = ""; } else value += char; } cells.push(value.trim()); return cells; };
  const headers = parseLine(lines[0]);
  return { headers, rows: lines.slice(1).map((line) => Object.fromEntries(headers.map((header, index) => [header, parseLine(line)[index] ?? ""]))) };
}
function inferMapping(headers: string[]): Mapping { return Object.fromEntries(fieldLabels.map((field) => { const header = headers.find((item) => aliases[field.key].some((alias) => normalize(item) === normalize(alias))) ?? headers.find((item) => aliases[field.key].some((alias) => normalize(item).includes(normalize(alias)))); return [field.key, header ?? "__none"]; })) as Mapping; }
function asOfCheck(row: RawRow, mapping: Mapping): { status: AsOfStatus; reason: string } {
  const predictionRaw = readMapped(row, mapping, "predictionTime");
  const prediction = toTimestamp(predictionRaw);
  if (!predictionRaw?.trim()) return { status: "MISSING_EVIDENCE", reason: "予測時刻が未指定" };
  if (prediction === null) return { status: "MISSING_EVIDENCE", reason: "予測時刻の形式が不正" };
  const inputs = [["オッズ", readMapped(row, mapping, "oddsObservedAt")], ["特徴量", readMapped(row, mapping, "featureAsOf")]] as const;
  const malformed = inputs.find(([, raw]) => raw?.trim() && toTimestamp(raw) === null);
  if (malformed) return { status: "MISSING_EVIDENCE", reason: `${malformed[0]}時点の形式が不正` };
  const available = inputs.map(([name, raw]) => [name, toTimestamp(raw)] as const).filter(([, time]) => time !== null);
  if (!available.length) return { status: "MISSING_EVIDENCE", reason: "オッズ・特徴量の時点が未指定" };
  const leaked = available.find(([, time]) => (time as number) > prediction);
  return leaked ? { status: "FAIL", reason: `${leaked[0]}時点が予測時刻より後` } : { status: "PASS", reason: "入力時点を確認" };
}
function normalizeRows(rawRows: RawRow[], mapping: Mapping) {
  let rejected = 0;
  const valid = rawRows.flatMap((row, index) => {
    const date = normalizeDate(readMapped(row, mapping, "date")); const probability = parseProbability(readMapped(row, mapping, "probability")); const probabilityKind = toProbabilityKind(readMapped(row, mapping, "probabilityKind"));
    if (!date || probability === null || probabilityKind === "unknown") { rejected += 1; return []; }
    const odds = toNumber(readMapped(row, mapping, "odds")); const payout = toNumber(readMapped(row, mapping, "payout")); const asOf = asOfCheck(row, mapping);
    return [{ date, raceId: readMapped(row, mapping, "raceId") || `row-${index + 1}`, venue: readMapped(row, mapping, "venue") || "未設定", modelId: readMapped(row, mapping, "modelId") || "未指定", probabilityKind, probability, shadowScore: toNumber(readMapped(row, mapping, "shadowScore")), odds: odds && odds > 1 ? odds : null, won: isWinner(readMapped(row, mapping, "won")), payout: payout && payout > 0 ? payout : null, asOfStatus: asOf.status, asOfReason: asOf.reason }];
  }).sort((left, right) => left.date.localeCompare(right.date));
  return { valid, rejected };
}
function normalizeProbabilities(values: number[]) { const safe = values.map((value) => Math.max(value, EPS)); const total = safe.reduce((sum, value) => sum + value, 0); return safe.map((value) => value / total); }
function logPool(model: number[], market: number[], marketWeight: number) { return normalizeProbabilities(model.map((value, index) => Math.exp((1 - marketWeight) * Math.log(Math.max(value, EPS)) + marketWeight * Math.log(Math.max(market[index], EPS))))); }
function marketShadow(rows: ResearchRow[], marketWeight: number): { coverage: { eligibleRaces: number; skippedRaces: number }; strategies: Record<MarketStrategy, MarketMetrics> } {
  const races = new Map<string, ResearchRow[]>(); rows.forEach((row) => races.set(row.raceId, [...(races.get(row.raceId) ?? []), row]));
  const values: Record<MarketStrategy, { loss: number[]; brier: number[] }> = { odds_only: { loss: [], brier: [] }, model_only: { loss: [], brier: [] }, blend: { loss: [], brier: [] } }; let skipped = 0;
  races.forEach((runners) => { if (runners.length < 2 || runners.some((row) => row.odds === null) || runners.filter((row) => row.won).length !== 1) { skipped += 1; return; } const winner = runners.findIndex((row) => row.won); const market = normalizeProbabilities(runners.map((row) => 1 / (row.odds as number))); const model = normalizeProbabilities(runners.map((row) => row.probability)); const methods: Record<MarketStrategy, number[]> = { odds_only: market, model_only: model, blend: logPool(model, market, marketWeight) }; (Object.keys(methods) as MarketStrategy[]).forEach((method) => { const p = methods[method]; values[method].loss.push(-Math.log(Math.max(p[winner], EPS))); values[method].brier.push(p.reduce((sum, value, index) => sum + (value - Number(index === winner)) ** 2, 0)); }); });
  const summary = (value: { loss: number[]; brier: number[] }): MarketMetrics => ({ races: value.loss.length, logLoss: value.loss.length ? value.loss.reduce((sum, item) => sum + item, 0) / value.loss.length : null, brier: value.brier.length ? value.brier.reduce((sum, item) => sum + item, 0) / value.brier.length : null });
  return { coverage: { eligibleRaces: values.odds_only.loss.length, skippedRaces: skipped }, strategies: { odds_only: summary(values.odds_only), model_only: summary(values.model_only), blend: summary(values.blend) } };
}
function gridSearchMarketWeight(rows: ResearchRow[]) {
  const candidates = Array.from({ length: 21 }, (_, index) => Number((index * .05).toFixed(2))).map((weight) => ({ weight, metrics: marketShadow(rows, weight).strategies.blend }));
  const eligible = candidates.filter((candidate) => candidate.metrics.logLoss !== null && candidate.metrics.brier !== null);
  if (!eligible.length) return { selectedWeight: null, selected: null, candidates, reason: "全頭オッズ・一意の勝者・as-of検査通過を満たす同一レースがないため、重みを選択しません。" };
  const selected = eligible.reduce((best, item) => item.metrics.logLoss! < best.metrics.logLoss! || (item.metrics.logLoss === best.metrics.logLoss && item.metrics.brier! < best.metrics.brier!) ? item : best);
  return { selectedWeight: selected.weight, selected: selected.metrics, candidates, reason: "選択範囲の履歴内でblendの平均Log lossを最小化し、同値ではBrierが小さい候補を選択します。未来期間の採用判断には別途walk-forwardが必要です。" };
}
function calibration(rows: ResearchRow[]) {
  const details = Array.from({ length: 10 }, (_, index) => { const low = index / 10; const high = (index + 1) / 10; const bucket = rows.filter((row) => row.probability >= low && (index === 9 ? row.probability <= high : row.probability < high)); if (!bucket.length) return null; const predicted = bucket.reduce((sum, row) => sum + row.probability, 0) / bucket.length; const observed = bucket.filter((row) => row.won).length / bucket.length; return { label: `${Math.round(low * 100)}–${Math.round(high * 100)}%`, predicted, observed, ideal: predicted, count: bucket.length, gap: predicted - observed }; }).filter((item): item is { label: string; predicted: number; observed: number; ideal: number; count: number; gap: number } => Boolean(item));
  return { details, ece: rows.length ? details.reduce((sum, item) => sum + Math.abs(item.gap) * item.count / rows.length, 0) : null };
}
function analyze(rows: ResearchRow[], fractionalKelly: number) {
  let capital = 100_000; let peak = capital;
  const curve = rows.map((row) => { const edge = row.odds ? row.probability * row.odds - 1 : null; const rawKelly = row.odds && edge && edge > 0 ? edge / (row.odds - 1) : 0; const stake = row.payout === null ? 0 : Math.floor(Math.min(capital * .02, capital * rawKelly * fractionalKelly) / 100) * 100; const profit = row.payout === null ? 0 : row.won ? stake * (row.payout - 1) : -stake; capital += profit; peak = Math.max(peak, capital); return { ...row, capital, drawdown: peak ? (capital - peak) / peak : 0, stake, profit }; });
  const brier = rows.length ? rows.reduce((sum, row) => sum + (row.probability - Number(row.won)) ** 2, 0) / rows.length : null; const logLoss = rows.length ? rows.reduce((sum, row) => sum - (row.won ? Math.log(Math.max(row.probability, EPS)) : Math.log(Math.max(1 - row.probability, EPS))), 0) / rows.length : null; const payouts = curve.filter((row) => row.payout !== null); const staked = payouts.reduce((sum, row) => sum + row.stake, 0); const returned = payouts.reduce((sum, row) => sum + row.stake + row.profit, 0);
  return { curve, brier, logLoss, hitRate: rows.length ? rows.filter((row) => row.won).length / rows.length : null, roi: staked > 0 ? returned / staked - 1 : null, payoutCoverage: payouts.length, maxDrawdown: curve.length ? Math.min(...curve.map((row) => row.drawdown)) : null };
}
function scoreComparison(rows: ResearchRow[]) { const paired = rows.filter((row) => row.probabilityKind === "truth_calibrated" && row.shadowScore !== null); if (!paired.length) return { paired, summary: null }; const x = paired.map((row) => row.shadowScore as number); const y = paired.map((row) => row.probability); const xMean = x.reduce((a, b) => a + b, 0) / x.length; const yMean = y.reduce((a, b) => a + b, 0) / y.length; const numerator = x.reduce((sum, item, index) => sum + (item - xMean) * (y[index] - yMean), 0); const denominator = Math.sqrt(x.reduce((sum, item) => sum + (item - xMean) ** 2, 0) * y.reduce((sum, item) => sum + (item - yMean) ** 2, 0)); return { paired, summary: { count: paired.length, scoreMean: xMean, probabilityMean: yMean, correlation: denominator ? numerator / denominator : null, observedRate: paired.filter((row) => row.won).length / paired.length } }; }
function isProfile(value: unknown): value is MappingProfile { if (!value || typeof value !== "object") return false; const item = value as Partial<MappingProfile>; return typeof item.name === "string" && Array.isArray(item.headers) && Boolean(item.mapping) && typeof item.mapping === "object"; }

export default function ResearchWorkbenchPage() {
  const [headers, setHeaders] = useState<string[]>([]); const [rawRows, setRawRows] = useState<RawRow[]>([]); const [mapping, setMapping] = useState<Mapping>({} as Mapping); const [fileName, setFileName] = useState("未選択"); const [kind, setKind] = useState<ProbabilityKind>("truth_calibrated"); const [venue, setVenue] = useState("all"); const [modelId, setModelId] = useState("all"); const [dateStart, setDateStart] = useState(""); const [dateEnd, setDateEnd] = useState(""); const [fractionalKelly, setFractionalKelly] = useState(.25); const [marketWeight, setMarketWeight] = useState(.5); const [marketStrategy, setMarketStrategy] = useState<MarketStrategy>("blend"); const [analysisTab, setAnalysisTab] = useState<AnalysisTab>("metrics"); const [notice, setNotice] = useState<string | null>(null); const [profileName, setProfileName] = useState(""); const [profiles, setProfiles] = useState<MappingProfile[]>(() => readStorage(PROFILE_STORAGE_KEY, []));
  useEffect(() => { localStorage.setItem(PROFILE_STORAGE_KEY, JSON.stringify(profiles)); }, [profiles]);
  const imported = useMemo(() => normalizeRows(rawRows, mapping), [rawRows, mapping]);
  const asOf = useMemo(() => ({ PASS: imported.valid.filter((row) => row.asOfStatus === "PASS").length, MISSING_EVIDENCE: imported.valid.filter((row) => row.asOfStatus === "MISSING_EVIDENCE").length, FAIL: imported.valid.filter((row) => row.asOfStatus === "FAIL").length }), [imported.valid]);
  const asOfDetails = useMemo(() => imported.valid.filter((row) => row.asOfStatus !== "PASS"), [imported.valid]);
  const asOfReasons = useMemo(() => Object.entries(asOfDetails.reduce<Record<string, number>>((result, row) => ({ ...result, [row.asOfReason]: (result[row.asOfReason] ?? 0) + 1 }), {})).sort((a, b) => b[1] - a[1]), [asOfDetails]);
  const dates = useMemo(() => imported.valid.map((row) => row.date).sort(), [imported.valid]); const kinds = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.probabilityKind))), [imported.valid]); const venues = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.venue))).sort(), [imported.valid]); const models = useMemo(() => Array.from(new Set(imported.valid.map((row) => row.modelId))).sort(), [imported.valid]);
  const filtered = useMemo(() => imported.valid.filter((row) => row.asOfStatus === "PASS" && row.probabilityKind === kind && (venue === "all" || row.venue === venue) && (modelId === "all" || row.modelId === modelId) && (!dateStart || row.date >= dateStart) && (!dateEnd || row.date <= dateEnd)), [imported.valid, kind, venue, modelId, dateStart, dateEnd]);
  const metrics = useMemo(() => analyze(filtered, fractionalKelly), [filtered, fractionalKelly]); const calibrationResult = useMemo(() => calibration(filtered), [filtered]); const comparison = useMemo(() => scoreComparison(imported.valid.filter((row) => row.asOfStatus === "PASS")), [imported.valid]); const marketRows = useMemo(() => filtered.filter((row) => row.probabilityKind === "truth_calibrated"), [filtered]); const market = useMemo(() => marketShadow(marketRows, marketWeight), [marketRows, marketWeight]); const gridSearch = useMemo(() => gridSearchMarketWeight(marketRows), [marketRows]); const requiredMissing = fieldLabels.filter((field) => field.required && (!mapping[field.key] || mapping[field.key] === "__none")); const chartData = metrics.curve.map((row) => ({ date: row.date, capital: row.capital, drawdown: Number((row.drawdown * 100).toFixed(2)) }));
  const onUpload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".csv")) { setNotice("この研究画面はCSVのみをブラウザ内で読み込みます。"); return; } if (file.size > 20 * 1024 * 1024) { setNotice("CSVは20MB以下に分割してください。外部送信はしません。"); return; } const parsed = parseCsv(await file.text()); setHeaders(parsed.headers); setRawRows(parsed.rows); setMapping(inferMapping(parsed.headers)); setFileName(file.name); setVenue("all"); setModelId("all"); setDateStart(""); setDateEnd(""); setNotice("列マッピングとas-of検査を確認してください。確率種別が不明な行は除外します。"); };
  const saveProfile = () => { const name = profileName.trim(); if (!name || !headers.length) { setNotice("プロファイル名とCSVヘッダーが必要です。"); return; } const profile = { id: `${Date.now()}`, name, headers, mapping, savedAt: Date.now() }; setProfiles((current) => [profile, ...current.filter((item) => item.name !== name)].slice(0, 12)); setProfileName(""); setNotice(`マッピングプロファイル「${name}」をこのブラウザへ保存しました。`); };
  const applyProfile = (profile: MappingProfile) => { const missing = profile.headers.filter((header) => !headers.includes(header)); if (missing.length) { setNotice(`プロファイル「${profile.name}」は現在のCSVと一致しません（不足: ${missing.slice(0, 3).join("、")}）。`); return; } setMapping(profile.mapping); setNotice(`プロファイル「${profile.name}」を適用しました。`); };
  const exportProfiles = () => { const payload: MappingProfileExport = { format: "keiba-lab-research-mapping-profiles-v1", exportedAt: new Date().toISOString(), profiles }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "keiba-trace-mapping-profiles.json"; link.click(); URL.revokeObjectURL(url); setNotice(`${profiles.length}件のマッピングプロファイルをJSONへ出力しました。`); };
  const importProfiles = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const payload = JSON.parse(await file.text()) as Partial<MappingProfileExport>; if (payload.format !== "keiba-lab-research-mapping-profiles-v1" || !Array.isArray(payload.profiles)) throw new Error("format"); const accepted = payload.profiles.filter(isProfile).map((profile) => ({ ...profile, id: `${Date.now()}-${profile.name}`, savedAt: Number(profile.savedAt) || Date.now() })); if (!accepted.length) throw new Error("profiles"); setProfiles((current) => [...accepted, ...current.filter((currentProfile) => !accepted.some((item) => item.name === currentProfile.name))].slice(0, 12)); setNotice(`${accepted.length}件のマッピングプロファイルをJSONから読み込みました。`); } catch { setNotice("プロファイルJSONの形式が不正です。KEIBA TRACEのエクスポートファイルを選択してください。"); } finally { event.target.value = ""; } };
  const applyGridSearch = () => { if (gridSearch.selectedWeight === null) { setNotice(gridSearch.reason); return; } setMarketWeight(gridSearch.selectedWeight); setMarketStrategy("blend"); setNotice(`この選択範囲でLog lossが最小のblend重み ${gridSearch.selectedWeight.toFixed(2)} を適用しました。未来期間での採用判断にはwalk-forward評価が必要です。`); };
  const tabClass = (active: boolean) => `rounded px-3 py-2 text-sm ${active ? "bg-[#2f766a] text-white" : "border border-[#456357] text-[#c4d7ca]"}`;

  return <main className="min-h-screen bg-[#101719] px-4 py-6 text-[#ecf2ed] md:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 border-b border-[#315247] pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold tracking-[0.2em] text-[#8bb89a]">KEIBA TRACE / RESEARCH WORKBENCH</p><h1 className="mt-2 text-3xl font-semibold">検証用バックテスト分析</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#b5c1b9]">TRUTH PANEL校正済み確率、未校正shadow score、WHAT-IFシナリオ勝率を分離したまま、時点固定・市場比較・再現可能なCSV分析を行います。</p></div><Link href="/" className="inline-flex items-center gap-2 self-start rounded border border-[#527566] px-3 py-2 text-sm text-[#d8e9dd] hover:bg-[#1d3029]"><ArrowLeft size={15} /> KEIBA TRACEへ戻る</Link></header>
    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-3"><FileSpreadsheet className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">CSVを読み込む</h2><p className="mt-1 text-sm text-[#aebbb2]">必須: 開催日、確率種別、予測確率、確定1着フラグ。オッズ・払戻倍率は実データがある場合だけ集計します。</p></div></div><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded bg-[#2f766a] px-4 py-2 text-sm font-medium text-white"><Upload size={15} /> CSVを選択<input className="hidden" type="file" accept=".csv,text/csv" onChange={onUpload} /></label><span className="ml-3 text-sm text-[#aebbb2]">{fileName}</span>{notice && <p className="mt-3 rounded border border-[#80663c] bg-[#332919] px-3 py-2 text-sm text-[#e9d2a0]">{notice}</p>}</div><aside className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2 text-[#8cc4a0]"><ShieldCheck size={17} /><span className="text-sm font-semibold">分離・時点固定ルール</span></div><ul className="mt-3 space-y-2 text-sm leading-5 text-[#b5c1b9]"><li>• 校正済み確率はブラウザ側で再校正しません。</li><li>• shadow scoreは順位・市場類似性だけに使います。</li><li>• WHAT-IFは実測確率・市場比較へ混ぜません。</li><li>• as-ofがPASS以外の行は品質評価から除外します。</li></ul></aside></section>
    {headers.length > 0 && <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">列マッピングと再利用プロファイル</h2><p className="mt-1 text-sm text-[#aebbb2]">{rawRows.length.toLocaleString()}行読み込み。{requiredMissing.length ? `必須項目 ${requiredMissing.map((field) => field.label).join("、")} を確認してください。` : "必須項目を確認済みです。"}</p></div><span className="rounded bg-[#20332b] px-2 py-1 text-xs text-[#a9d7b8]">有効 {imported.valid.length.toLocaleString()}行 / 除外 {imported.rejected.toLocaleString()}行</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{fieldLabels.map((field) => <label key={field.key} className="text-sm"><span className="mb-1 block text-[#b5c1b9]">{field.label}{field.required && <b className="ml-1 text-[#e9b7a1]">必須</b>}</span><select className="w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={mapping[field.key] ?? "__none"} onChange={(event) => setMapping((current) => ({ ...current, [field.key]: event.target.value }))}><option value="__none">未使用</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="mt-5 border-t border-[#315247] pt-4"><div className="flex flex-wrap gap-2"><input className="rounded border border-[#456357] bg-[#101719] px-3 py-2 text-sm text-[#ecf2ed]" value={profileName} onChange={(event) => setProfileName(event.target.value)} placeholder="例: JRA-VAN 成績CSV v1" /><button type="button" onClick={saveProfile} className="inline-flex items-center gap-2 rounded bg-[#2f766a] px-3 py-2 text-sm font-medium"><Save size={14} /> 現在の対応を保存</button><button type="button" onClick={exportProfiles} className="inline-flex items-center gap-2 rounded border border-[#456357] px-3 py-2 text-sm"><Download size={14} /> JSON出力</button><label className="inline-flex cursor-pointer items-center gap-2 rounded border border-[#456357] px-3 py-2 text-sm"><FileUp size={14} /> JSON読込<input className="hidden" type="file" accept="application/json,.json" onChange={importProfiles} /></label></div>{profiles.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{profiles.map((profile) => <span key={profile.id} className="inline-flex items-center gap-1 rounded border border-[#456357] bg-[#101719] px-2 py-1 text-xs"><button type="button" onClick={() => applyProfile(profile)} className="text-[#c7e5d0] hover:underline">{profile.name}</button><button type="button" onClick={() => setProfiles((current) => current.filter((item) => item.id !== profile.id))} aria-label={`${profile.name}を削除`} className="text-[#d98c78]"><Trash2 size={12} /></button></span>)}</div>}</div></section>}
    {imported.valid.length > 0 && <><section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#8cc4a0]" /><h2 className="font-semibold">評価範囲とas-of検査</h2></div><div className="mt-4 grid gap-3 md:grid-cols-5"><label className="text-sm text-[#b5c1b9]">開始日<input className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" type="date" min={dates[0]} max={dateEnd || dates.at(-1)} value={dateStart} onChange={(event) => setDateStart(event.target.value)} /></label><label className="text-sm text-[#b5c1b9]">終了日<input className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" type="date" min={dateStart || dates[0]} max={dates.at(-1)} value={dateEnd} onChange={(event) => setDateEnd(event.target.value)} /></label><label className="text-sm text-[#b5c1b9]">確率種別<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={kind} onChange={(event) => setKind(event.target.value as ProbabilityKind)}>{kinds.map((item) => <option key={item} value={item}>{kindLabel[item]}</option>)}</select></label><label className="text-sm text-[#b5c1b9]">競馬場<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={venue} onChange={(event) => setVenue(event.target.value)}><option value="all">全競馬場</option>{venues.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="text-sm text-[#b5c1b9]">モデルID<select className="mt-1 w-full rounded border border-[#456357] bg-[#101719] px-2 py-2 text-[#ecf2ed]" value={modelId} onChange={(event) => setModelId(event.target.value)}><option value="all">全モデル</option>{models.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded border border-[#315247] bg-[#101719] p-3"><span className="text-xs text-[#9bb0a4]">as-of PASS</span><strong className="ml-2 text-[#92d5aa]">{asOf.PASS}</strong></div><div className="rounded border border-[#315247] bg-[#101719] p-3"><span className="text-xs text-[#9bb0a4]">時点情報なし</span><strong className="ml-2 text-[#e7bc62]">{asOf.MISSING_EVIDENCE}</strong></div><div className="rounded border border-[#6e4138] bg-[#2c1d1a] p-3"><span className="text-xs text-[#d9a095]">as-of FAIL（除外）</span><strong className="ml-2 text-[#e89987]">{asOf.FAIL}</strong></div></div></section>
      <section className="flex flex-wrap gap-2"><button type="button" onClick={() => setAnalysisTab("metrics")} className={tabClass(analysisTab === "metrics")}><Activity className="mr-1 inline" size={14} /> 分析指標</button><button type="button" onClick={() => setAnalysisTab("asof")} className={tabClass(analysisTab === "asof")}><Search className="mr-1 inline" size={14} /> as-of原因分析 ({asOfDetails.length})</button></section>
      {analysisTab === "asof" ? <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-2"><Search className="mt-0.5 text-[#8cc4a0]" size={17} /><div><h2 className="font-semibold">as-of検査の原因分析</h2><p className="mt-1 text-sm text-[#aebbb2]">FAILとMISSINGは品質評価・市場比較から除外済みです。MISSINGは推測で補完せず、入力時点の追記対象として表示します。</p></div></div>{asOfDetails.length ? <><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{asOfReasons.map(([reason, count]) => <div key={reason} className="rounded border border-[#456357] bg-[#101719] p-3"><p className="text-xs text-[#9bb0a4]">{reason}</p><p className="mt-1 text-lg font-semibold">{count}行</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-[#456357] text-[#aebbb2]"><tr><th className="p-2">開催日</th><th className="p-2">レースID</th><th className="p-2">競馬場</th><th className="p-2">ステータス</th><th className="p-2">原因</th></tr></thead><tbody>{asOfDetails.slice(0, 100).map((row, index) => <tr key={`${row.raceId}-${index}`} className="border-b border-[#21372e]"><td className="p-2">{row.date}</td><td className="p-2">{row.raceId}</td><td className="p-2">{row.venue}</td><td className={`p-2 ${row.asOfStatus === "FAIL" ? "text-[#e89987]" : "text-[#e7bc62]"}`}>{row.asOfStatus}</td><td className="p-2">{row.asOfReason}</td></tr>)}</tbody></table></div></> : <p className="mt-4 rounded border border-dashed border-[#456357] px-4 py-5 text-sm text-[#aebbb2]">FAIL・MISSINGのレコードはありません。全ての有効行がas-of PASSです。</p>}</section> : <>
        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{[["対象行", filtered.length.toLocaleString()], ["Brier", metrics.brier?.toFixed(4) ?? "データなし"], ["Log loss", metrics.logLoss?.toFixed(4) ?? "データなし"], ["ECE", calibrationResult.ece?.toFixed(4) ?? "データなし"], ["実績的中率", metrics.hitRate === null ? "データなし" : `${(metrics.hitRate * 100).toFixed(1)}%`], ["ROI", metrics.roi === null ? "払戻なし" : `${(metrics.roi * 100).toFixed(1)}%`], ["最大DD", metrics.maxDrawdown === null ? "払戻なし" : `${(metrics.maxDrawdown * 100).toFixed(1)}%`]].map(([label, value]) => <div className="rounded-lg border border-[#315247] bg-[#17211f] p-4" key={label}><p className="text-xs text-[#9bb0a4]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</section>
        <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><Activity size={17} className="text-[#8cc4a0]" /><div><h2 className="font-semibold">確率校正曲線と理想線</h2><p className="text-xs text-[#aebbb2]">{kindLabel[kind]}のみ。ECEは確率帯の絶対gapを件数加重した研究指標です。</p></div></div><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={calibrationResult.details}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis dataKey="label" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis domain={[0, 1]} tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${Math.round(value * 100)}%`} /><Tooltip contentStyle={{ background: "#101719", border: "1px solid #456357" }} formatter={(value: number) => `${(value * 100).toFixed(1)}%`} /><Line type="monotone" dataKey="ideal" name="理想線（予測確率）" stroke="#9ba79f" strokeDasharray="5 4" dot={false} /><Line type="monotone" dataKey="observed" name="実績的中率" stroke="#68c197" strokeWidth={2} connectNulls /></LineChart></ResponsiveContainer></div><p className="mt-2 text-xs text-[#91a59a]">確率帯ごとの件数: {calibrationResult.details.map((row) => row.count).join(" / ") || "データなし"}</p></article><article className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-center gap-2"><BarChart3 size={17} className="text-[#8cc4a0]" /><div><h2 className="font-semibold">資金・ドローダウン</h2><p className="text-xs text-[#aebbb2]">確定払戻倍率のある履歴だけ。Fractional Kellyは研究用表示です。</p></div></div><label className="mt-3 block text-sm text-[#b5c1b9]">Fractional Kelly: {fractionalKelly.toFixed(2)}<input className="mt-2 w-full accent-[#5eb782]" type="range" min="0" max=".5" step=".05" value={fractionalKelly} onChange={(event) => setFractionalKelly(Number(event.target.value))} /></label><div className="mt-4 h-60">{metrics.payoutCoverage ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fill: "#aebbb2", fontSize: 10 }} /><YAxis yAxisId="capital" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis yAxisId="dd" orientation="right" tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={{ background: "#101719", border: "1px solid #456357" }} /><ReferenceLine yAxisId="dd" y={0} stroke="#6d8477" /><Area yAxisId="capital" type="monotone" dataKey="capital" name="資金" stroke="#68c197" fill="#68c197" fillOpacity={.12} /><Area yAxisId="dd" type="monotone" dataKey="drawdown" name="DD%" stroke="#d67a68" fill="#d67a68" fillOpacity={.15} /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-[#aebbb2]">確定単勝払戻倍率を読み込むと資金曲線を表示します。</div>}</div></article></section>
        <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-2"><LineChartIcon size={17} className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">Market shadow — odds-only / model-only / blend</h2><p className="mt-1 text-xs leading-5 text-[#aebbb2]">校正済みTRUTH PANEL確率と同一レース内の発走前単勝オッズを使うshadow比較です。未校正shadow scoreとWHAT-IFはこの評価へ含めません。</p></div></div><div className="mt-4 flex flex-wrap items-center gap-2">{(Object.keys(strategyLabel) as MarketStrategy[]).map((strategy) => <button key={strategy} type="button" onClick={() => setMarketStrategy(strategy)} className={tabClass(marketStrategy === strategy)}>{strategyLabel[strategy]}</button>)}<label className="ml-auto text-sm text-[#b5c1b9]">市場重み（blend）: {marketWeight.toFixed(2)}<input className="ml-2 align-middle accent-[#5eb782]" type="range" min="0" max="1" step=".05" value={marketWeight} onChange={(event) => setMarketWeight(Number(event.target.value))} /></label></div><div className="mt-4 grid gap-3 md:grid-cols-3">{(Object.keys(strategyLabel) as MarketStrategy[]).map((strategy) => <div key={strategy} className={`rounded border p-4 ${strategy === marketStrategy ? "border-[#69ad7e] bg-[#1c3028]" : "border-[#315247] bg-[#101719]"}`}><p className="text-sm font-semibold">{strategyLabel[strategy]}</p><p className="mt-2 text-xs text-[#9bb0a4]">対象レース {market.strategies[strategy].races}</p><p className="mt-1 text-sm">Log loss: {market.strategies[strategy].logLoss?.toFixed(4) ?? "データなし"}</p><p className="mt-1 text-sm">Brier: {market.strategies[strategy].brier?.toFixed(4) ?? "データなし"}</p></div>)}</div><div className="mt-5 rounded border border-[#456357] bg-[#101719] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-[#8cc4a0]" /><h3 className="font-semibold">blend市場重みのグリッドサーチ</h3></div><p className="mt-1 text-xs text-[#aebbb2]">0.00〜1.00を0.05刻みで探索し、現在の選択範囲内のLog loss最小値を候補として表示します。</p></div><button type="button" onClick={applyGridSearch} className="rounded bg-[#2f766a] px-3 py-2 text-sm font-medium">候補を適用</button></div><p className="mt-3 text-sm">選択候補: {gridSearch.selectedWeight === null ? "データなし" : `市場重み ${gridSearch.selectedWeight.toFixed(2)} / Log loss ${gridSearch.selected?.logLoss?.toFixed(4)} / Brier ${gridSearch.selected?.brier?.toFixed(4)}`}</p><p className="mt-1 text-xs text-[#91a59a]">{gridSearch.reason}</p><div className="mt-3 grid grid-cols-7 gap-1 text-[10px] text-[#aebbb2]">{gridSearch.candidates.map((candidate) => <span key={candidate.weight} className={`rounded px-1 py-1 text-center ${candidate.weight === gridSearch.selectedWeight ? "bg-[#315f4d] text-white" : "bg-[#1d2b25]"}`}>{candidate.weight.toFixed(2)}</span>)}</div></div><p className="mt-3 text-xs text-[#91a59a]">対象 {market.coverage.eligibleRaces}レース / 除外 {market.coverage.skippedRaces}レース。最適化結果はin-sample候補であり、採用判断は同一未来期間のwalk-forwardと統計検定で行います。</p></section>
        <section className="rounded-lg border border-[#315247] bg-[#17211f] p-5"><div className="flex items-start gap-2"><FlaskConical size={17} className="mt-0.5 text-[#8cc4a0]" /><div><h2 className="font-semibold">TRUTH PANEL × shadow score 比較</h2><p className="mt-1 text-xs leading-5 text-[#aebbb2]">同一行の校正済み確率と未校正scoreの関係を確認します。shadow scoreは確率・Brier・Log loss・ROIの計算には使用しません。</p></div></div>{comparison.summary ? <><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["ペア行数", comparison.summary.count.toLocaleString()], ["校正済み確率平均", `${(comparison.summary.probabilityMean * 100).toFixed(1)}%`], ["shadow score平均", comparison.summary.scoreMean.toFixed(3)], ["相関の参考値", comparison.summary.correlation === null ? "算出不可" : comparison.summary.correlation.toFixed(3)], ["ペア行の実績的中率", `${(comparison.summary.observedRate * 100).toFixed(1)}%`]].map(([label, value]) => <div key={label} className="rounded border border-[#315247] bg-[#101719] p-3"><p className="text-xs text-[#9bb0a4]">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 16, bottom: 10, left: 0 }}><CartesianGrid stroke="#315247" strokeDasharray="3 3" /><XAxis type="number" dataKey="shadowScore" name="未校正shadow score" tick={{ fill: "#aebbb2", fontSize: 11 }} /><YAxis type="number" dataKey="probability" name="校正済み確率" domain={[0, 1]} tick={{ fill: "#aebbb2", fontSize: 11 }} tickFormatter={(value) => `${Math.round(value * 100)}%`} /><ZAxis range={[45, 45]} /><Tooltip cursor={{ strokeDasharray: "3 3" }} contentStyle={{ background: "#101719", border: "1px solid #456357" }} formatter={(value: number, name: string) => name === "校正済み確率" ? `${(value * 100).toFixed(1)}%` : value.toFixed(3)} /><Scatter name="校正済み確率とshadow score" data={comparison.paired} fill="#e7bc62" /></ScatterChart></ResponsiveContainer></div></> : <p className="mt-4 rounded border border-dashed border-[#456357] px-4 py-5 text-sm text-[#aebbb2]">比較対象はありません。`truth_calibrated`と同一行の`shadow_score`をマッピングしてください。</p>}</section>
      </>}</>}
    {headers.length === 0 && <section className="rounded-lg border border-dashed border-[#456357] bg-[#17211f] p-10 text-center"><AlertTriangle className="mx-auto text-[#e7bc62]" /><h2 className="mt-3 font-semibold">CSVを選択すると研究用分析を開始できます</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-[#aebbb2]">JRA-VAN等から正当に取得・エクスポートした履歴を利用してください。確率・市場・払戻・時点情報が不足する場合は、推測せず対象外または入力不足として扱います。</p></section>}
  </div></main>;
}
