import React, { useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Clock3, Download, Filter, LoaderCircle, RefreshCw, RotateCcw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { DEFAULT_RACE_HISTORY_FILTERS, downloadRaceHistoryCsv, filterRaceHistory, type RaceHistoryFilters } from "@/lib/raceHistoryTools";

export type RaceHistorySource = { enabled: boolean; refreshMinutes: number; syncStartedAt: string | null; lastAttemptAt: string | null; lastSuccessAt: string | null; nextRetryAt: string | null; consecutiveFailures: number; lastError: string | null };
export type RaceHistoryRace = { raceKey: string; raceDate: string | null; organization: string | null; venue: string | null; raceNo: number | null; raceStatus: string | null; calibrationStatus: string | null; asOf: string | null; resultStatus: string | null; aiPickFinish: number | null; aiPickOutcome: string | null; comparedCount: number | null; exactMatches: number | null; meanAbsoluteRankError: number | null; winReturnRate: number | null; placeReturnRate: number | null; lastSyncedAt: string | null; confirmedAt: string | null };
export type RaceHistoryRun = { id: number; outcome: string; message: string | null; racesChecked: number; racesUpdated: number; finishedAt: string | null };
export type RaceHistoryData = { source: RaceHistorySource | null; races: RaceHistoryRace[]; recentRuns: RaceHistoryRun[] };

const dateTime = (iso: string | null) => !iso ? "未同期" : new Intl.DateTimeFormat("ja-JP", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(iso));
const metric = (value: number | null, digits = 1) => typeof value === "number" ? value.toFixed(digits) : "—";
type TrendSeries = { label: string; value: number | null }[];

function SparkLine({ series, label }: { series: TrendSeries; label: string }) {
  const available = series.filter((item): item is { label: string; value: number } => typeof item.value === "number");
  if (!available.length) return <div className="sync-spark-empty">確定済みの値が届くと、ここに推移を表示します。</div>;
  const values = available.map(item => item.value); const min = Math.min(...values); const max = Math.max(...values); const span = max - min || 1;
  const points = available.map((item, index) => `${12 + (index * 176) / Math.max(1, available.length - 1)},${64 - ((item.value - min) / span) * 46}`).join(" ");
  return <div className="sync-spark" aria-label={label}><svg viewBox="0 0 200 76" role="img" aria-label={label}><line x1="10" y1="64" x2="190" y2="64" /><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{available.map((item, index) => { const [x, y] = points.split(" ")[index].split(","); return <circle key={`${item.label}-${index}`} cx={x} cy={y} r="3.5" />; })}</svg><div><span>{available[0]?.label}</span><span>{available.at(-1)?.label}</span></div></div>;
}

export function RaceHistoryDashboardView({ data, loading = false, refreshing = false, onRefresh }: { data: RaceHistoryData | null; loading?: boolean; refreshing?: boolean; onRefresh?: () => void }) {
  const [filters, setFilters] = useState<RaceHistoryFilters>(DEFAULT_RACE_HISTORY_FILTERS);
  const state = data?.source; const races = data?.races ?? [];
  const venues = useMemo(() => Array.from(new Set(races.map(race => race.venue).filter((venue): venue is string => Boolean(venue)))).sort((left, right) => left.localeCompare(right, "ja")), [races]);
  const filteredRaces = useMemo(() => filterRaceHistory(races, filters), [races, filters]);
  const confirmed = filteredRaces.filter(race => race.resultStatus === "CONFIRMED");
  const compared = confirmed.reduce((sum, race) => sum + (race.comparedCount ?? 0), 0); const exact = confirmed.reduce((sum, race) => sum + (race.exactMatches ?? 0), 0);
  const meanErrorRows = confirmed.filter(race => race.meanAbsoluteRankError !== null); const meanError = meanErrorRows.length ? meanErrorRows.reduce((sum, race) => sum + (race.meanAbsoluteRankError ?? 0), 0) / meanErrorRows.length : null;
  const roiRows = confirmed.flatMap(race => [race.winReturnRate, race.placeReturnRate]).filter((value): value is number => typeof value === "number"); const averageRoi = roiRows.length ? roiRows.reduce((sum, value) => sum + value, 0) / roiRows.length : null;
  const recent = filteredRaces.slice(-18); const errorState = Boolean(state?.lastError); const isRunning = refreshing || Boolean(state?.syncStartedAt);
  const updateFilters = (patch: Partial<RaceHistoryFilters>) => setFilters(current => ({ ...current, ...patch }));
  return <section className="sync-history-dashboard" aria-label="AI精度と仮想ROIの履歴"><header className="sync-history-heading"><div><span className="eyebrow">AI OUTCOME ARCHIVE</span><h2>精度と回収率の履歴</h2><p>single_pick_aiが提供した**確定済み**の公式着順・払戻だけを集計します。未確定のレースは推定値へ置き換えません。</p></div><div className="sync-history-actions"><button type="button" className="sync-export-button" onClick={() => downloadRaceHistoryCsv(filteredRaces, filters)} disabled={!filteredRaces.length || isRunning}><Download size={15} /> CSV出力</button><button type="button" className="sync-refresh-button" onClick={onRefresh} disabled={isRunning}>{isRunning ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />} {isRunning ? "同期中" : "今すぐ同期"}</button></div></header>
    <div className="sync-filter-panel" aria-label="履歴フィルター"><label>期間（開始）<input type="date" value={filters.from} max={filters.to || undefined} onChange={event => updateFilters({ from: event.target.value })} /></label><label>期間（終了）<input type="date" value={filters.to} min={filters.from || undefined} onChange={event => updateFilters({ to: event.target.value })} /></label><label>競馬場<select value={filters.venue} onChange={event => updateFilters({ venue: event.target.value })}><option value="">すべての競馬場</option>{venues.map(venue => <option key={venue} value={venue}>{venue}</option>)}</select></label><button type="button" className="sync-filter-reset" onClick={() => setFilters(DEFAULT_RACE_HISTORY_FILTERS)}><RotateCcw size={13} /> 条件をリセット</button></div>
    <div className="sync-filter-summary"><span><Filter size={12} /> 表示対象 <strong>{filteredRaces.length}</strong> / {races.length} 件</span><span>{filters.venue || "全競馬場"} · {filters.from || "開始指定なし"}〜{filters.to || "終了指定なし"}</span></div>
    <div className={`sync-status-strip ${isRunning ? "is-running" : ""}`} role="status"><div className={isRunning ? "sync-status-icon running" : errorState ? "sync-status-icon error" : "sync-status-icon"}>{isRunning ? <LoaderCircle className="spin" size={17} /> : errorState ? <AlertTriangle size={17} /> : <CheckCircle2 size={17} />}</div><div><span>最終同期成功</span><strong>{dateTime(state?.lastSuccessAt ?? null)}</strong></div><div><span>次回確認</span><strong>{state?.nextRetryAt ? dateTime(state.nextRetryAt) : state ? `${state.refreshMinutes}分ごと` : "初回同期前"}</strong></div><div><span>状態</span><strong className={isRunning ? "sync-status-running" : ""}>{isRunning && <LoaderCircle className="spin" size={13} />}{isRunning ? "バックグラウンド同期中" : errorState ? `再試行 ${state?.consecutiveFailures ?? 0}回目` : state ? "正常" : "同期設定を確認中"}</strong></div>{errorState && <p>{state?.lastError}</p>}</div>
    <div className="sync-kpi-grid"><article><span>CONFIRMED RACES</span><strong>{confirmed.length}</strong><small>フィルター後の確定済み結果のみ</small></article><article><span>RANK EXACT</span><strong>{compared ? `${((exact / compared) * 100).toFixed(1)}%` : "—"}</strong><small>{compared ? `${exact} / ${compared} 頭が順位一致` : "照合対象なし"}</small></article><article><span>MEAN RANK ERROR</span><strong>{metric(meanError)}</strong><small>平均順位差（小さいほど良い）</small></article><article><span>VIRTUAL ROI</span><strong>{averageRoi === null ? "—" : `${averageRoi.toFixed(1)}%`}</strong><small>確認できる単勝・複勝のみ</small></article></div>
    <div className="sync-trend-grid"><article className="sync-trend-card brass"><div><span>RANK ACCURACY TREND</span><strong>{compared ? `${((exact / compared) * 100).toFixed(1)}%` : "未確定"}</strong></div><SparkLine label="AI順位と公式着順の一致率推移" series={recent.map(race => ({ label: `${race.venue ?? "—"}${race.raceNo ?? ""}R`, value: race.comparedCount ? ((race.exactMatches ?? 0) / race.comparedCount) * 100 : null }))} /></article><article className="sync-trend-card mint"><div><span>VIRTUAL ROI TREND</span><strong>{averageRoi === null ? "未確定" : `${averageRoi.toFixed(1)}%`}</strong></div><SparkLine label="確認できる仮想ROIの推移" series={recent.map(race => ({ label: `${race.venue ?? "—"}${race.raceNo ?? ""}R`, value: race.winReturnRate ?? race.placeReturnRate }))} /></article></div>
    <div className="sync-history-table-wrap"><div className="sync-history-table-heading"><div><span className="eyebrow">RACE LEDGER</span><h3>レース別の確定記録</h3></div><span>{filteredRaces.length}件を表示</span></div>{loading ? <div className="sync-dashboard-empty"><RefreshCw className="spin" size={18} /> 同期履歴を読み込んでいます。</div> : !filteredRaces.length ? <div className="sync-dashboard-empty"><Clock3 size={18} /> 条件に一致する履歴はありません。</div> : <div className="sync-ledger">{[...filteredRaces].reverse().map(race => <article key={race.raceKey} className={race.resultStatus === "CONFIRMED" ? "confirmed" : "pending"}><div className="sync-race-title"><strong>{race.venue ?? "開催地未取得"} {race.raceNo ? `${race.raceNo}R` : ""}</strong><small>{race.raceDate ?? "日付未取得"} · {race.calibrationStatus}</small></div><div><span>公式結果</span><strong>{race.resultStatus === "CONFIRMED" ? "確定" : "未確定"}</strong></div><div><span>本命</span><strong>{race.aiPickOutcome ?? "結果待ち"}{race.aiPickFinish ? ` · ${race.aiPickFinish}着` : ""}</strong></div><div><span>順位一致</span><strong>{race.comparedCount ? `${race.exactMatches ?? 0}/${race.comparedCount}` : "—"}</strong></div><div><span>単勝ROI</span><strong>{race.winReturnRate === null ? "—" : `${race.winReturnRate.toFixed(0)}%`}</strong></div><div><span>複勝ROI</span><strong>{race.placeReturnRate === null ? "—" : `${race.placeReturnRate.toFixed(0)}%`}</strong></div><time>{dateTime(race.lastSyncedAt)}</time></article>)}</div>}</div>
    {data?.recentRuns.length ? <details className="sync-run-history"><summary><Activity size={14} /> 同期実行履歴（直近{data.recentRuns.length}件）</summary>{data.recentRuns.map(run => <p key={run.id}><time>{dateTime(run.finishedAt)}</time><strong>{run.outcome}</strong><span>{run.message ?? "詳細なし"}</span></p>)}</details> : null}
  </section>;
}

export function RaceHistoryDashboard() {
  const dashboard = trpc.raceSync.dashboard.useQuery(undefined, { refetchInterval: 60_000, refetchOnWindowFocus: true });
  const refresh = trpc.raceSync.refreshNow.useMutation({ onSuccess: () => dashboard.refetch() });
  const refreshing = refresh.isPending || Boolean(dashboard.data?.source?.syncStartedAt);
  return <RaceHistoryDashboardView data={dashboard.data ?? null} loading={dashboard.isLoading} refreshing={refreshing} onRefresh={() => refresh.mutate()} />;
}
